import { describe, it } from 'mocha';
import { strict as assert } from 'assert';
import { DirectedGraphHierarchicalLayout } from '../index.js';

describe('Wrapper', () => {
    it('special case 0', () => {
        const layout = new DirectedGraphHierarchicalLayout();
        const graph = layout.createGraph(2);
        graph.addEdge(0, 1);
        layout.setGraph(graph);
        layout.layoutGraph();
        const svg = layout.render();
        const expected = `<svg width="48.526911934581186" height="110.75230867899737" viewBox="0 0 48.526911934581186 110.75230867899737" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(24.263455967290593,23.556349186104047) scale(1.0)">
    <!-- Node: node0 -->
    <g class="node" id="node0">
      <title>node0</title>
      <ellipse cx="0" cy="0" rx="16.263455967290593" ry="15.556349186104047" fill="none" stroke="black"/>
    </g>
    <!-- Node: node1 -->
    <g class="node" id="node1">
      <title>node1</title>
      <ellipse cx="0" cy="63.63961030678928" rx="16.263455967290593" ry="15.556349186104047" fill="none" stroke="black"/>
    </g>
    <!-- Edge: edge1 (node0 -> node1) -->
    <g class="edge" id="edge1">
      <title>node0->node1</title>
      <line x1="9.70921363846253e-16" y1="15.856349186104048" x2="1.6881690900939898e-15" y2="36.0697168277983" stroke="black"/>
      <polygon points="1.075845690520313e-15,46.0697168277983 -3.4999999999999996,36.0697168277983 3.500000000000002,36.0697168277983 1.075845690520313e-15,46.0697168277983" fill="black" stroke="black"/>
    </g>
  </g>
</svg>
`;
        assert(svg === expected);
    });
});