import { describe, it } from 'mocha';
import { strict as assert } from 'assert';
import { createDirectedGraph, DirectedGraphHierarchicalLayout } from '../index.js';

describe('Wrapper', () => {
    it('special case 0', () => {
        const graph = createDirectedGraph(2);
        graph.addEdge(0, 1);
        const layout = new DirectedGraphHierarchicalLayout();
        layout.setGraph(graph);
        layout.layoutGraph();
        const svg = layout.render();
        const expected = `<svg width="47.8276609256791" height="115.70991191958765" viewBox="0 0 47.8276609256791 115.70991191958765" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(23.91383046283955,23.91383046283955) scale(1.0)">
    <!-- Node: node0 -->
    <g class="node" id="node0">
      <title>node0</title>
      <circle cx="0" cy="0" r="15.913830462839549" fill="none" stroke="black"/>
    </g>
    <!-- Node: node1 -->
    <g class="node" id="node1">
      <title>node1</title>
      <circle cx="0" cy="67.88225099390856" r="15.913830462839549" fill="none" stroke="black"/>
    </g>
    <!-- Edge: edge1 (node0 -> node1) -->
    <g class="edge" id="edge1">
      <title>node0->node1</title>
      <line x1="9.92810778911715e-16" y1="16.21383046283955" x2="1.7100585051594516e-15" y2="39.954876238182074" stroke="black"/>
      <polygon points="1.097735105585775e-15,49.954876238182074 -3.4999999999999996,39.954876238182074 3.500000000000002,39.954876238182074 1.097735105585775e-15,49.954876238182074" fill="black" stroke="black"/>
    </g>
  </g>
</svg>
`;
        assert(svg === expected);
    });
});